import type { Metrics } from "./schemas.js";

export function generateAntiRules(m: Metrics): string {
  const rules: string[] = [];

  if (m.overprompting.ultrathinks > 5) {
    rules.push(
      `- Stop saying "ultrathink" / "think harder". You've done it ${m.overprompting.ultrathinks} times. The model is the same model either way.`,
    );
  }
  if (m.attitude.fixItLazy > 10) {
    rules.push(
      `- "fix it" / "just do it" is not a prompt (${m.attitude.fixItLazy} occurrences). Describe the desired end state in one sentence.`,
    );
  }
  if (m.attitude.corrections > 20) {
    rules.push(
      `- ${m.attitude.corrections} corrections logged. Front-load constraints in the first prompt instead of saying "no, actually" mid-flow.`,
    );
  }
  if (m.promptHabits.promptsWithPaste > 10) {
    rules.push(
      `- ${m.promptHabits.promptsWithPaste} prompts contained pasted blobs (${m.promptHabits.pastedBlobCount} total). Reference files by path; don't paste them in.`,
    );
  }
  if (m.danger.noVerify + m.danger.gitResetHard + m.danger.forcePush > 0) {
    rules.push(
      `- Avoid destructive shortcuts: --no-verify (${m.danger.noVerify}), git reset --hard (${m.danger.gitResetHard}), force push (${m.danger.forcePush}). Fix the root cause; don't bypass the check.`,
    );
  }
  if (m.timePatterns.lateNight > 20) {
    rules.push(
      `- ${m.timePatterns.lateNight} prompts between midnight and 5am. Sleep is also a productivity tool.`,
    );
  }
  if (m.overprompting.importantShouts > 30) {
    rules.push(
      `- ${m.overprompting.importantShouts} ALL-CAPS directives ("IMPORTANT", "MUST"). Once is emphasis; thirty times is noise.`,
    );
  }
  if (m.promptHabits.oneWordPrompts > 30) {
    rules.push(
      `- ${m.promptHabits.oneWordPrompts} one-word prompts. "continue" / "go" / "yes" hide the actual goal — be one sentence more specific.`,
    );
  }
  if (m.attitude.thxCount > 20) {
    rules.push(
      `- ${m.attitude.thxCount} "thx/ty/perfect" reply turns. Roll the next instruction into the same message; the model isn't tracking your gratitude.`,
    );
  }

  if (!rules.length) {
    rules.push(
      "- (No glaring anti-patterns detected. Suspicious. Try harder.)",
    );
  }

  const date = new Date().toISOString().slice(0, 10);
  return [
    "# CLAUDE.md — anti-rules",
    "",
    `_Generated by claude-roast on ${date} based on your real history. Stop doing these things._`,
    "",
    "## Things I keep doing wrong",
    "",
    ...rules,
    "",
  ].join("\n");
}
